# Generated by Django 5.1.5 on 2025-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_usuario_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
